version: '{build}'
os: Visual Studio 2017
configuration: Release
platform: x86

branches:
  except:
    - coverity_scan

before_build:
- cmd: |
    echo Installing dependencies...
    git submodule update --init --recursive
    echo Running cmake ..
    cmake -G "Visual Studio 15 2017" -DCMAKE_INSTALL_PREFIX=%P% -DBUILD_TESTS=ON

build:
  project: ALL_BUILD.vcxproj
  parallel: true
  verbosity: normal

test_script:
  - Release\test_sexp.exe

# EOF #
